const PrivacyPolicy = () => {
    return (
        <div className="design-text-black max-w-3xl mx-auto px-4 py-8">
            <h1 className="text-3xl text-center font-bold mb-4">Privacy Policy</h1>
            <p className="text-xl font-bold ">Your privacy is critically important to us. </p> 
            <p className="mb-4"> It is <b><b>cricquest.in</b>&#39;s</b> policy to respect your privacy regarding any information we may collect while operating our website. This Privacy Policy applies to <b>https://www.<b>cricquest.in</b></b> & (hereinafter, "us", "we", or "<b>cricquest.in</b>"). We respect your privacy and are committed to protecting personally identifiable information you may provide us through the Website. We have adopted this privacy policy ("Privacy Policy") to explain what information may be collected on our Website, how we use this information, and under what circumstances we may disclose the information to third parties. This Privacy Policy applies only to information we collect through the Website and does not apply to our collection of information from other sources.</p>
            
            <h2 className="text-xl font-bold mb-2">Website Visitors</h2>
            <p className="mb-4">Like most website operators, <b>cricquest.in</b> collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. <b>cricquest.in</b>&#39;s purpose in collecting non-personally identifying information is to better understand how <b>cricquest.in</b>&#39;s visitors use its website. From time to time, <b>cricquest.in</b> may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website.<b>cricquest.in</b> also collects potentially personally-identifying information like Internet Protocol (IP) addresses for logged in users and for users leaving comments on <b>cricquest.in</b> blog posts. <b>cricquest.in</b> only discloses logged in user and commenter IP addresses under the same circumstances that it uses and discloses personally-identifying information as described below.</p>

            <h2 className="text-xl font-bold mb-2">Security</h2>
            <p className="mb-4">The security of your Personal Information is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Information, we cannot guarantee its absolute security.</p>

            <h2 className="text-xl font-bold mb-2">Advertisements</h2>
            <p className="mb-4">Our website uses third-party vendors, including Google, that use cookies to serve ads based on a user&#39;s previous visits to our website or other websites. Google&#39;s use of advertising cookies enables it and its partners to serve ads to our users based on their visit to our site and/or other sites on the Internet.
                Users may opt out of personalised advertising by visiting Ads Settings. 
                If you haven&#39;t opted out of third-party ad serving, the cookies of other third-party vendors or ad networks may also be used to serve ads on our site. We notify our site visitors of the third-party vendors and ad networks serving ads on our site, and provide links to their appropriate websites. Users may visit those websites to opt out of the use of cookies for personalised advertising (if the vendor or ad network offers this capability), or they can opt out of some third-party vendors&#39; uses of cookies for personalised advertising by visiting www.aboutads.info.
                Please note that our privacy policy may vary based on publisher sites and laws in different countries. For guidance on drafting a privacy policy, please review resources such as the Network Advertising Initiative. For more information on cookie consent notices, please visit cookiechoices.org.</p>

            <h2 className="text-xl font-bold mb-2">Link to external sites</h2>
            <p className="mb-4">Our Service may contain links to external sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy and terms and conditions of every site you visit.<br />We have no control over, and assume no responsibility for the content, privacy policies or practices of any third party sites, products or services.</p>
            
            <h2 className="text-xl font-bold mb-2"><b>cricquest.in</b> uses Google AdWords for remarketing</h2>
            <p className="mb-4"><b>cricquest.in</b> uses the remarketing services to advertise on third party websites (including Google) to previous visitors to our site. It could mean that we advertise to previous visitors who haven't completed a task on our site, for example using the contact form to make an enquiry. This could be in the form of an advertisement on the Google search results page, or a site in the Google Display Network. Third-party vendors, including Google, use cookies to serve ads based on someone's past visits. Of course, any data collected will be used in accordance with our own privacy policy and Google's privacy policy. You can set preferences for how Google advertises to you using the Google Ad Preferences page, and if you want to you can opt out of interest-based advertising entirely by cookie settings or permanently using a browser plugin. </p>

            <h2 className="text-xl font-bold mb-2">Protection of Certain Personally-Identifying Information</h2>
            <p className="mb-4"><b>cricquest.in</b> discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on <b>cricquest.in</b>'s behalf or to provide services available at <b>cricquest.in</b>'s website, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using <b>cricquest.in</b>’s website, you consent to the transfer of such information to them. <b>cricquest.in</b> will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors and affiliated organizations, as described above, <b>cricquest.in</b> discloses potentially personally-identifying and personally-identifying information only in response to a governmental request, or when <b>cricquest.in</b> believes in good faith that disclosure is reasonably necessary to protect the property or rights of <b>cricquest.in</b>, third parties or the public at large.
If you are a registered user of <b>cricquest.in</b> and have supplied your email address. <b>cricquest.in</b> may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with what's going on with <b>cricquest.in</b> and our products. We primarily use our blog to communicate this type of information, so we expect to keep this type of email to a minimum. If you send us a request (for example via a support email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. <b>cricquest.in</b> takes all measures reasonably necessary to protect against the unauthorized access, use, alteration or destruction of potentially personally-identifying and personally-identifying information.</p>

            <h2 className="text-xl font-bold mb-2">Aggregated Statistics</h2>
            <p className="mb-4"><b>cricquest.in</b> may collect statistics about the behavior of visitors to its website. <b>cricquest.in</b> may display this information publicly or provide it to others. However, <b>cricquest.in</b> does not disclose your personally-identifying information.</p>

            <h2 className="text-xl font-bold mb-2">Affiliate Disclosure</h2>
            <p className="mb-4">This site uses affiliate links and does earn a commission from certain links. This does not affect your purchases or the price you may pay.
</p>

            <h2 className="text-xl font-bold mb-2">Aggregated Statistics</h2>
            <p className="mb-4">To enrich and perfect your online experience, <b>cricquest.in</b> uses "Cookies", similar technologies and services provided by others to display personalized content, appropriate advertising and store your preferences on your computer.
A cookie is a string of information that a website stores on a visitor's computer, and that the visitor's browser provides to the website each time the visitor returns. <b>cricquest.in</b> uses cookies to help <b>cricquest.in</b> identify and track visitors, their usage of <b>https://www.<b>cricquest.in</b>/</b>, and their website access preferences. <b>cricquest.in</b> visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using <b>cricquest.in</b>'s websites, with the drawback that certain features of <b>cricquest.in</b>'s websites may not function properly without the aid of cookies.
By continuing to navigate our website without changing your cookie settings, you hereby acknowledge and agree to <b>cricquest.in</b>'s use of cookies.
</p>


        </div>
    );
};

export default PrivacyPolicy;
